CELib code completion and VDB SourceConfig Bugfix
delphix/mongo-plugin pull request #11
Opened 2023-02-16 09:45 UTC by ayesharustgi-delphix

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2023-02-16 15:17 UTC, manaskhandeshe-delphix requested changes

2023-02-16 15:17 UTC, manaskhandeshe-delphix commented on src/libs/ce_lib/helpers.py
> +    for i in range(len(arr1)):
Following test-cases are failing with this logic.

compare_version('6.2.1', '6.1.5', '>')  ==> it returns False instead of True
compare_version('6.1.7', '6.2.0', '<')  ==> it returns False instead of True

2023-02-16 15:17 UTC, manaskhandeshe-delphix commented on src/libs/mongodb_lib/mongosync.py
>                          f"supported. Only v1.0.0 supported."
Instead of 1.0.0, leverage the constanct  MongoSyncConstants.mongosync_supported_version

2023-02-16 15:17 UTC, manaskhandeshe-delphix commented on src/libs/mongodb_lib/mongosync.py
>              error_msg = "MongoDB version less than 6.0.0 not supported with " \
Instead of 6.0.0, let's leverage the constant MongoSyncConstants.mongodb_supported_version

2023-02-20 06:31 UTC, ayesharustgi-delphix commented on src/libs/ce_lib/helpers.py
> +    arr1 = v1.split(".")
The `compare_version` function now supports all combinations > , < , >= , <= , ==.

2023-02-20 06:32 UTC, ayesharustgi-delphix commented on src/libs/ce_lib/helpers.py
> +    for i in range(len(arr1)):
Resolved.

2023-02-20 06:32 UTC, ayesharustgi-delphix commented on src/libs/mongodb_lib/mongosync.py
>                          f"supported. Only v1.0.0 supported."
Done!

2023-02-20 06:32 UTC, ayesharustgi-delphix commented on src/libs/mongodb_lib/mongosync.py
>              error_msg = "MongoDB version less than 6.0.0 not supported with " \
Done!

2023-02-20 06:44 UTC, manaskhandeshe-delphix approved these changes

2023-02-20 06:45 UTC, merged