CE-79 MongoDB Plugin Docs : Addition of description of expected backup files format
delphix/mongo-plugin pull request #19
Opened 2023-03-13 11:50 UTC by chetanchoudhary-delphix

1. Offlinemongodump specific validation
When dsource type is selected to offlinemongodump, make sure that following parameters are not empty.
Backup Metadata file name
Backup directory for mongodump (Also check if its a directory)

2. Sharded specific validation
When dsource type is selected to shardedsource, make sure that following parameters are not empty.
If Cluster to Cluster Sync is not selected,
Backup Metadata File name
Config Server Backup File (Also check if it's a tar / tar.gz file)
Shard Backup Files (Also check if it's a tar / tar.gz file)

3. When dsource type is selected to nonshardedsource, make sure that following parameters are not empty.
Backup Metadata File name
Config Server Backup File (Also check if it's a tar / tar.gz file)

2023-03-14 04:45 UTC, manaskhandeshe-delphix approved these changes

2023-03-14 04:46 UTC, manaskhandeshe-delphix submitted a review, later dismissed

2023-03-14 16:00 UTC, manaskhandeshe-delphix requested changes

2023-03-15 06:16 UTC, manaskhandeshe-delphix requested changes

2023-03-15 06:16 UTC, manaskhandeshe-delphix commented on src/operations/common.py
> +        is_supported = backup_file.endswith(
We could create a generic function inside os_lib - check_file_type() which implements this logic and checek_ops_center_backup_files() should call that function.

2023-03-15 06:16 UTC, manaskhandeshe-delphix commented on src/operations/common.py
> +                            f"Shard backup file: {shard_backup} should be present on host. "
check_ops_center_backup_files() throws one out of two exceptions.

1. "Config server backup file should be present on host. Given backup file not available. "
2. "Config server backup file should be of type .tar / .tar.gz format. "


So exc will already have the exact error message. We should display that message except _either or_.

2023-03-15 15:31 UTC, manaskhandeshe-delphix approved these changes

2023-03-15 15:36 UTC, manaskhandeshe-delphix commented
Code looks okay. Before merge, let's hear more from @ayesharustgi-delphix

2023-03-16 05:16 UTC, ayesharustgi-delphix commented on src/operations/common.py
> +                )
why are we raising error  twice? Once inside `check_mongodump_utility_dir` and once outside. 
Either we can change return type of to function to boolean or we can use the error we raised inside.

2023-03-16 05:16 UTC, ayesharustgi-delphix commented on src/operations/common.py
> +                )
same here

2023-03-16 05:16 UTC, ayesharustgi-delphix commented on src/operations/common.py
> +                        )
same here too

2023-03-16 18:00 UTC, chetanchoudhary-delphix commented on src/operations/common.py
> +                )
Updating this by adding the raise_exception flag in the function.

2023-03-20 05:35 UTC, merged