CE-227 Bug Fix - IncompleteTransactionHistory error thrown by mongod
delphix/mongo-plugin pull request #25
Opened 2023-03-31 08:43 UTC by ayesharustgi-delphix

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2023-04-03 05:01 UTC, manaskhandeshe-delphix requested changes

2023-04-03 05:01 UTC, manaskhandeshe-delphix commented on src/mongopy.py
> +        mongosync_obj.resume_sync()
Let's wait for say 30 seconds, verify if RESUME state is seen.

2023-04-04 05:49 UTC, ayesharustgi-delphix commented on src/mongopy.py
> +                    mongosync_obj.pause_sync()
Done!

2023-04-04 05:49 UTC, ayesharustgi-delphix commented on src/mongopy.py
> +                    mongo_obj.fsyncLock(
Done!

2023-04-04 05:49 UTC, ayesharustgi-delphix commented on src/mongopy.py
> +        mongosync_obj.resume_sync()
Done!

2023-04-04 07:29 UTC, manaskhandeshe-delphix approved these changes

2023-04-04 07:29 UTC, merged