Linked Source Sizing
delphix/mongo-plugin pull request #41
Opened 2023-04-20 13:29 UTC by ayesharustgi-delphix

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2023-04-21 11:42 UTC, manaskhandeshe-delphix requested changes

2023-04-21 11:42 UTC, manaskhandeshe-delphix commented on src/libs/ce_lib/os_lib/os_lib.py
>          Return disk filesystem structure of the host.
Since it is "du" command that is being used the description could be on the similar ground. 
For example, Get file space usage or get disk usage statistics

2023-04-21 11:42 UTC, manaskhandeshe-delphix commented on src/operations/common.py
> +def check_stale_mount(os_lib_obj: OSLib, mount_location: str):
Since this function also unmounts stale mount, name should depict the same.

For example, check_and_unmount_stale_mount_location()

2023-04-21 11:42 UTC, manaskhandeshe-delphix commented on src/operations/common.py
> +    :return: RunBashResponse
It would be helpful to elaborate what kind of response text it is going to be.

2023-04-24 09:13 UTC, ayesharustgi-delphix commented on src/libs/ce_lib/os_lib/os_lib.py
>          Return disk filesystem structure of the host.
Resolved

2023-04-24 09:13 UTC, ayesharustgi-delphix commented on src/operations/common.py
> +def check_stale_mount(os_lib_obj: OSLib, mount_location: str):
Resolved

2023-04-24 11:42 UTC, manaskhandeshe-delphix approved these changes

2023-04-25 06:26 UTC, merged